### PR TITLE
Set API key in CLI config and download subtitles using a freetext query

### PR DESCRIPTION
**Pull request by Realiserad**

### CODE REVIEW

**Comment by rocketteering** [comment]
@dusking is this PR and repo dead? This seems like a good addition, don't know why there is nothing happening.

I was thinking of adding a similar feature of simplifying the downloading (love this project), but I'd want to know if you're around to merge pr's

**Comment by rocketteering** [comment]
@Realiserad are you still using your fork or package personally? I was thinking (no promises) that I'd might consider forking this repo, updating it with some stuff and publishing it to PyPi.

**Comment by Realiserad** [comment]
@IlmariKu Yes :)

**Comment by dusking** [comment]
Hey @IlmariKu sorry for the delayed response. Please see my comments.

**Comment by Realiserad** [comment]
@dusking I missed your message. Did you intend to quote me? I cannot see any comments? 😊

**Pull request merged**
